import { StyleSheet } from 'react-native';
import { theme } from '../../../theme';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  safeArea: {
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
    zIndex: 2,
    elevation: 20,
  },
  panel: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: theme.borderRadius.xl,
    borderTopRightRadius: theme.borderRadius.xl,
    paddingTop: theme.spacing[2],
    paddingHorizontal: theme.spacing[4],
    paddingBottom: theme.spacing[4],
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 16,
  },
  dragHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.gray200,
    marginBottom: theme.spacing[4],
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing[5],
  },
  headerIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#E0F7FA',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing[3],
    flexShrink: 0,
  },
  headerTextCol: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
  },
  title: {
    fontSize: theme.typography.fontSize.lg,
    fontWeight: '600',
    color: theme.colors.gray800,
  },
  subtitle: {
    marginTop: 4,
    fontSize: theme.typography.fontSize.sm,
    lineHeight: 20,
    color: theme.colors.gray500,
  },
  optionsBlock: {
    width: '100%',
    marginBottom: theme.spacing[2],
  },
  optionPressable: {
    width: '100%',
    marginBottom: theme.spacing[3],
  },
  optionLast: {
    marginBottom: 0,
  },
  optionPressed: {
    opacity: 0.9,
  },
  optionCard: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    marginBottom: theme.spacing[2],
    width: '100%',
    minHeight: 64,
    paddingVertical: theme.spacing[3],
    paddingHorizontal: theme.spacing[4],
    backgroundColor: theme.colors.backgroundSecondary,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  optionIconGallery: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(57, 175, 188, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing[3],
    flexShrink: 0,
  },
  optionIconCamera: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(31, 99, 122, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing[3],
    flexShrink: 0,
  },
  optionTextCol: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    marginRight: theme.spacing[2],
    justifyContent: 'center',
  },
  optionTitle: {
    fontSize: theme.typography.fontSize.base,
    fontWeight: '600',
    color: theme.colors.black,
  },
  optionSub: {
    marginTop: 4,
    fontSize: theme.typography.fontSize.sm,
    lineHeight: 18,
    color: theme.colors.gray600,
  },
  optionChevronText: {
    flexShrink: 0,
    width: 28,
    fontSize: 24,
    fontWeight: '300',
    color: theme.colors.gray500,
    textAlign: 'center',
    lineHeight: 28,
  },
  cancelWrap: {
    marginTop: theme.spacing[4],
  },
  cancelButton: {
    minHeight: 48,
  },
  pressableAutofill: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
});
