import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.backgroundSecondary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[3],
    paddingTop: theme.spacing[5],
    backgroundColor: theme.colors.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderLight,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: theme.borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -theme.spacing[1],
    backgroundColor: theme.colors.gray100,
  },
  headerTitle: {
    flex: 1,
    marginHorizontal: theme.spacing[2],
    fontSize: theme.typography.fontSize.lg,
    fontWeight: '700',
    color: theme.colors.gray800,
    textAlign: 'center',
  },
  cartIconWrap: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCartBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: theme.colors.error,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  headerCartBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.white,
  },
  listContent: {
    paddingHorizontal: theme.spacing[4],
    paddingTop: theme.spacing[3],
    paddingBottom: theme.spacing[4],
  },
  addressCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(57, 175, 188, 0.1)',
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing[3],
    marginBottom: theme.spacing[4],
  },
  addressIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(57, 175, 188, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing[3],
  },
  addressTexts: {
    flex: 1,
  },
  addressTitle: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: '700',
    color: theme.colors.gray800,
    marginBottom: theme.spacing[1],
  },
  addressSub: {
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.gray500,
  },
  addAddress: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: '600',
    color: theme.colors.link,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing[3],
    marginBottom: theme.spacing[3],
    shadowColor: theme.colors.black,
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  thumb: {
    width: 72,
    height: 72,
    borderRadius: theme.borderRadius.base,
    backgroundColor: theme.colors.gray100,
  },
  rowBody: {
    flex: 1,
    marginLeft: theme.spacing[3],
    marginRight: theme.spacing[2],
  },
  productName: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: '700',
    color: theme.colors.gray800,
    marginBottom: theme.spacing[1],
  },
  productMeta: {
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.gray500,
    marginBottom: theme.spacing[1],
  },
  productPrice: {
    fontSize: theme.typography.fontSize.base,
    fontWeight: '700',
    color: theme.colors.gray800,
  },
  qtyWrap: {
    alignSelf: 'flex-start',
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: theme.colors.borderLight,
    marginVertical: theme.spacing[2],
  },
  footer: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing[4],
    paddingTop: theme.spacing[3],
    paddingBottom: theme.spacing[4],
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderLight,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing[2],
  },
  summaryLabel: {
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray600,
  },
  summaryValue: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: '600',
    color: theme.colors.gray800,
  },
  freeText: {
    color: theme.colors.success,
    fontWeight: '600',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: theme.spacing[2],
  },
  totalLabel: {
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray500,
  },
  totalValue: {
    fontSize: theme.typography.fontSize['2xl'],
    fontWeight: '700',
    color: theme.colors.gray800,
  },
  checkoutBtn: {
    marginTop: theme.spacing[4],
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.primary,
    paddingVertical: theme.spacing[3],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkoutLabel: {
    fontSize: theme.typography.fontSize.base,
    fontWeight: '700',
    color: theme.colors.textOnPrimary,
  },
  emptyText: {
    textAlign: 'center',
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray500,
    marginTop: theme.spacing[8],
  },
  hydratingFooter: {
    paddingVertical: theme.spacing[2],
    alignItems: 'center',
  },
});

export default styles;
