export const SUCCESS = 'success';
export const FAILED = 'failed';

//API Endpoints
export const API_ENDPOINTS = {
  LOGIN: '/auth/login',
  SIGNUP: '/signup',
  APP_CONFIG:'/auth/app-config'
};

export const DATABASE_NAME = 'GroceryAppDB';

export const DB_TABLES ={
  USER_TABLE: 'users',
  CONFIG_TABLE: 'app_config'
};

export const CONFIG_KEYS = {
  SMALL_CART_MIN_AMOUNT:'SMALL_CART_MIN_AMOUNT',
  ALLOW_PINCODES:'ALLOW_PINCODES',
  DEFAULT_LATITUDE:'DEFAULT_LATITUDE',
  DEFAULT_LONGITUDE:'DEFAULT_LONGITUDE',
  RECEIPT_FOOTER_MESSAGE:'RECEIPT_FOOTER_MESSAGE',
  GATEWAY_SECRET_KEY:'GATEWAY_SECRET_KEY',
  REFER_URL:'REFER_URL',
  REFER_MESSAGE:'REFER_MESSAGE',
  ORDER_HELP_ENABLE_TIME:'ORDER_HELP_ENABLE_TIME',
  ADD_COMPLAIN_ENABLE:'ADD_COMPLAIN_ENABLE',
  VIEW_COMPLAIN_ENABLE:'VIEW_COMPLAIN_ENABLE',
  EXPORT_LOG_FILE_ENABLE:'EXPORT_LOG_FILE_ENABLE',
};

export const SERVICE_AUTH_CREDENTIALS = 'com.united.uis';