import { StyleSheet } from 'react-native';
import { theme } from '../../../theme';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  container: {
    paddingHorizontal: theme.spacing[5],
    paddingTop: theme.spacing[6],
    paddingBottom: theme.spacing[8],
  },
  header: {
    backgroundColor: theme.colors.secondary,
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing[5],
    marginBottom: theme.spacing[5],
    overflow: 'hidden',
  },
  headerIcon: {
    width: 48,
    height: 48,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing[4],
  },
  headerCopy: {
    marginBottom: theme.spacing[2],
  },
  eyebrow: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.bold,
    letterSpacing: 1.1,
    color: '#BDEDF1',
    marginBottom: theme.spacing[1],
  },
  title: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize['2xl'],
    lineHeight: 30,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.white,
  },
  subtitle: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.sm,
    lineHeight: 21,
    color: '#D7F2F4',
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: theme.spacing[3],
  },
  sectionTitle: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.lg,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.gray800,
  },
  sectionCount: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.gray500,
  },
  controls: {
    marginBottom: theme.spacing[5],
  },
  searchBox: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: theme.spacing[3],
    marginBottom: theme.spacing[3],
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray800,
    marginLeft: theme.spacing[2],
    paddingVertical: 0,
  },
  filterRow: {
    alignItems: 'center',
    gap: theme.spacing[2],
  },
  filterChip: {
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[2],
  },
  filterChipActive: {
    borderColor: theme.colors.primary,
    backgroundColor: '#E2F5F7',
  },
  filterChipText: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.semibold,
    color: theme.colors.gray600,
  },
  filterChipTextActive: {
    color: theme.colors.secondary,
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[2],
  },
  sortText: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.semibold,
    color: theme.colors.secondary,
    marginLeft: theme.spacing[1],
  },
  planCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    padding: theme.spacing[4],
    marginBottom: theme.spacing[4],
    shadowColor: theme.colors.black,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  planCardCurrent: {
    borderColor: theme.colors.primary,
    borderWidth: 2,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.14,
  },
  currentBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[1],
    backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.sm,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: theme.spacing[1],
    marginBottom: theme.spacing[3],
  },
  currentBadgeText: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xxs,
    fontWeight: theme.typography.fontWeight.bold,
    letterSpacing: 0.7,
    color: theme.colors.white,
  },
  planTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  planIconWrap: {
    width: 48,
    height: 48,
    borderRadius: theme.borderRadius.md,
    backgroundColor: '#E2F5F7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing[3],
  },
  planHeading: {
    flex: 1,
    minWidth: 0,
  },
  planType: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.base,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.gray800,
  },
  planOffer: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.gray500,
    marginTop: 2,
  },
  priceBlock: {
    alignItems: 'flex-end',
    marginLeft: theme.spacing[2],
  },
  price: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xl,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.secondary,
  },
  priceSuffix: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xxs,
    color: theme.colors.gray500,
    marginTop: 1,
  },
  speedPanel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.backgroundSecondary,
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing[3],
    marginTop: theme.spacing[4],
  },
  speedLabel: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xxs,
    fontWeight: theme.typography.fontWeight.bold,
    letterSpacing: 0.6,
    color: theme.colors.gray500,
    marginBottom: 3,
  },
  speedValue: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.lg,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.primaryDark,
  },
  secondaryValue: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.sm,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.gray800,
  },
  speedDivider: {
    width: 1,
    height: 30,
    backgroundColor: theme.colors.borderLight,
    marginHorizontal: theme.spacing[2],
  },
  benefitsList: {
    marginTop: theme.spacing[4],
    gap: theme.spacing[2],
  },
  benefitRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  benefitText: {
    flex: 1,
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.sm,
    lineHeight: 20,
    color: theme.colors.gray600,
    marginLeft: theme.spacing[2],
  },
  channelSection: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.borderLight,
    marginTop: theme.spacing[4],
    paddingTop: theme.spacing[3],
  },
  channelTitle: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xs,
    fontWeight: theme.typography.fontWeight.semibold,
    color: theme.colors.gray700,
    marginBottom: theme.spacing[2],
  },
  channelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing[2],
  },
  channelTile: {
    width: '22%',
    alignItems: 'center',
  },
  channelImage: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: theme.borderRadius.base,
    backgroundColor: theme.colors.gray50,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  channelChip: {
    width: '100%',
    alignItems: 'center',
    fontSize: theme.typography.fontSize.xxs,
    backgroundColor: '#F0F8F9',
    textAlign: 'center',
    marginTop: theme.spacing[1],
    paddingHorizontal: theme.spacing[2],
    paddingVertical: theme.spacing[1],
  },
  channelName: {
    flexShrink: 1,
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.secondary,
    marginLeft: theme.spacing[1],
  },
  stateCard: {
    minHeight: 220,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing[6],
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  stateTitle: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.lg,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.gray800,
    marginTop: theme.spacing[3],
    textAlign: 'center',
  },
  stateText: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.sm,
    lineHeight: 21,
    color: theme.colors.gray500,
    textAlign: 'center',
    marginTop: theme.spacing[2],
  },
  retryButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.base,
    paddingHorizontal: theme.spacing[5],
    paddingVertical: theme.spacing[3],
    marginTop: theme.spacing[4],
  },
  retryText: {
    fontFamily: theme.typography.fontFamily.primary,
    fontSize: theme.typography.fontSize.sm,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.white,
  },
});
