import { StyleSheet } from 'react-native';
import { theme } from '../../../theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.backgroundSecondary,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: theme.spacing[4],
    paddingTop: theme.spacing[5],
    paddingBottom: theme.spacing[5],
  },
  header: {
    marginBottom: theme.spacing[5],
  },
  eyebrow: {
    fontSize: theme.typography.fontSize.xs,
    color: theme.colors.primary,
    letterSpacing: 1,
    fontWeight: theme.typography.fontWeight.bold,
    marginBottom: theme.spacing[1],
  },
  title: {
    fontSize: theme.typography.fontSize['2xl'],
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.gray800,
    marginBottom: theme.spacing[2],
  },
  subtitle: {
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray600,
    lineHeight: 20,
  },
  heroCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing[5],
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    marginBottom: theme.spacing[4],
  },
  heroArtwork: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing[4],
    minHeight: 120,
  },
  heroArtworkCircleLarge: {
    width: 96,
    height: 96,
    borderRadius: theme.borderRadius.full,
    backgroundColor: '#E0F7FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroArtworkCircleSmallLeft: {
    position: 'absolute',
    left: '22%',
    top: 18,
    width: 44,
    height: 44,
    borderRadius: theme.borderRadius.full,
    backgroundColor: '#EEF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroArtworkCircleSmallRight: {
    position: 'absolute',
    right: '22%',
    bottom: 12,
    width: 40,
    height: 40,
    borderRadius: theme.borderRadius.full,
    backgroundColor: '#ECFDF5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroIconWrap: {
    width: 64,
    height: 64,
    borderRadius: theme.borderRadius.full,
    backgroundColor: '#E0F7FA',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing[4],
  },
  heroTitle: {
    fontSize: theme.typography.fontSize.xl,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.gray800,
    marginBottom: theme.spacing[2],
  },
  heroText: {
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray600,
    lineHeight: 20,
  },
  featureGrid: {
    gap: theme.spacing[3],
    marginBottom: theme.spacing[4],
  },
  featureCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    padding: theme.spacing[4],
  },
  featureIconWrap: {
    width: 44,
    height: 44,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.gray50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing[2],
  },
  featureTitle: {
    fontSize: theme.typography.fontSize.base,
    color: theme.colors.gray800,
    fontWeight: theme.typography.fontWeight.bold,
    marginBottom: theme.spacing[1],
  },
  featureSubtitle: {
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray600,
    lineHeight: 20,
  },
  calloutCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    padding: theme.spacing[4],
    marginBottom: theme.spacing[3],
  },
  calloutIconWrap: {
    width: 44,
    height: 44,
    borderRadius: theme.borderRadius.full,
    backgroundColor: '#E0F7FA',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing[3],
  },
  calloutContent: {
    flex: 1,
    minWidth: 0,
  },
  calloutTitle: {
    fontSize: theme.typography.fontSize.base,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.gray800,
    marginBottom: theme.spacing[1],
  },
  calloutText: {
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray600,
    lineHeight: 20,
  },
  footer: {
    marginTop: 'auto',
    paddingTop: theme.spacing[3],
    gap: theme.spacing[3],
  },
  helperText: {
    textAlign: 'center',
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.gray500,
    lineHeight: 20,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing[2],
  },
  shareButtonText: {
    color: theme.colors.textOnPrimary,
  },
});

export default styles;
